mysql:
  image: mysql
  container_name: $CONTAINER_NAME
  restart: always
  volumes:
    - $LOCAL_VOLUME:/var/lib/mysql
  environment:
    MYSQL_DATABASE: $MYSQL_DATABASE
    MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
  ports:
    - $LOCAL_PORT:3306
